sonar.projectKey=smart-city-dashboard
sonar.projectName=Smart City Operations & Asset Management Dashboard
sonar.projectVersion=1.0.0

sonar.sources=app,components,lib
sonar.tests=__tests__

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,jest.config.ts,playwright.config.ts,next.config.ts,tailwind.config.ts
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx
